name: Build and Publish

on:
  push:
    branches:
      - '*'
      - '!master'

jobs:
  build-and-push-docker-image:
    name: Build and Push Docker Image [feature]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: "docker: Login to Container Registry"
        id: docker-login
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - run: echo "TAG=${GITHUB_REF#refs/*/}" | tee -a $GITHUB_ENV
      # - run: echo "BRANCH=$(git branch -a --contains ${{ env.TAG }} | grep -v HEAD | cut -d '/' -f3)" | tee -a $GITHUB_ENV
      - run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Build image and push to Docker Hub tagged with the branchname
        uses: docker/build-push-action@v2
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./docker
          platforms: linux/amd64,linux/arm64
          # Note: tags has to be all lower-case
          tags: | # ${{ env.TAG }}${{ env.BRANCH }}
            jakoberpf/zerotier-bridge:${{ env.BRANCH }} 
            ghcr.io/jakoberpf/zerotier-bridge:${{ env.BRANCH }}
          # build on feature branches, push only on master branch
          push: ${{ github.ref != 'refs/heads/master' }}
          build-args: |
            BRANCH=${{ env.BRANCH }}
          # | sed -r 's,/,-,g'

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}